name: Reddit Post
on:
  schedule:
    # Morning peak: 7-10 AM EST (12-15 UTC)
    - cron: '0 12 * * 1-5'   # 8:00 AM EST (12:00 UTC) - Monday to Friday
    - cron: '30 13 * * 1-5'  # 9:30 AM EST (13:30 UTC) - Monday to Friday
    - cron: '0 15 * * 1-5'   # 11:00 AM EST (15:00 UTC) - Monday to Friday
    
    # Lunch break peak: 11 AM-2 PM EST (15-18 UTC)
    - cron: '30 16 * * 1-5'  # 12:30 PM EST (16:30 UTC) - Monday to Friday
    - cron: '0 18 * * 1-5'   # 2:00 PM EST (18:00 UTC) - Monday to Friday
    
    # Evening peak: 6-10 PM EST (22-02 UTC)
    - cron: '0 22 * * 1-5'   # 6:00 PM EST (22:00 UTC) - Monday to Friday
    - cron: '30 23 * * 1-5'  # 7:30 PM EST (23:30 UTC) - Monday to Friday
    - cron: '0 1 * * 2-6'    # 9:00 PM EST (01:00 UTC next day) - Monday to Friday
    - cron: '30 2 * * 2-6'   # 10:30 PM EST (02:30 UTC next day) - Monday to Friday
  workflow_dispatch: # Allow manual triggering

jobs:
  post_to_reddit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run Crypto Market Analysis
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          python crypto.py

      - name: Run Penny Stock Screener
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          python main.py