name: Reddit Post
on:
  schedule:
    - cron: '30 14 * * *'  # 9:30 AM EST (14:30 UTC)
    - cron: '0 17 * * *'   # 12:00 PM EST (17:00 UTC)
    - cron: '0 5 * * *'    # 12:00 AM EST (05:00 UTC)
  workflow_dispatch: # Allow manual triggering

jobs:
  post_to_reddit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run Crypto Market Analysis
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          python crypto.py

      - name: Run Penny Stock Screener
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
        run: |
          python main.py